# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eat Good Food Group
email: webmaster@eatgoodfoodgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Strong foods is a new venture by the eat good food group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strong-foods.com" # the base hostname & protocol for your site
twitter_username_eamonns: eamonnschipper
facebook_username_eamonns: EamonnsADublinChipper
instagram_username_eamonns: EamonnsADublinChipper

# Build settings
markdown: kramdown

# Configure prose.io.
prose:
  rooturl: '_posts'
  siteurl: 'http://eatgoodfood.github.io/strongfoods'
  relativeLinks: 'http://eatgoodfood.github.io/strongfoods/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - CNAME
    - /_layouts
    - /_includes
    - /_plugins
    - /_sass
  siteurl: "http://strong-foods.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Tags"
          options:
            - name: "Update"
              value: "update"