# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eat Good Food Group
email: webmaster@eatgoodfoodgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Strong foods is a new venture by the eat good food group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strong-foods.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
